# Video Subtitle Generation Configuration
# Copy this file to config.yaml and update with your values

# Google Cloud Configuration
gcp:
  project_id: "your-project-id"
  location: "us-central1"
  credentials_path: ""  # Leave empty to use default credentials

# Vertex AI Configuration
vertex_ai:
  model: "gemini-2.0-pro-exp"
  temperature: 0.2
  max_output_tokens: 8192
  top_p: 0.95

# Storage Configuration
storage:
  bucket_name: ""  # Optional: leave empty for local processing
  input_prefix: "input-videos"
  chunks_prefix: "chunks"
  subtitles_prefix: "subtitles"
  output_prefix: "output-videos"

# Processing Configuration
processing:
  chunk_duration: 60  # seconds
  max_parallel_workers: 5
  retry_attempts: 3
  retry_delay: 5  # seconds
  cleanup_temp_files: true
  
# Subtitle Configuration
subtitles:
  source_language: "auto"  # auto-detect
  target_language: "en"    # default target
  formats: ["srt", "vtt"]
  burn_subtitles: false
  hindi_translation_method: "direct"  # "direct" or "via_english"
  supported_languages: ["en", "hi", "bn"]
  
# Output Configuration
output:
  video_codec: "libx264"
  audio_codec: "aac"
  quality_preset: "medium"
  
# Logging Configuration
logging:
  level: "INFO"
  log_file: "logs/subtitle_generator.log"
  max_file_size: "10MB"
  backup_count: 5

# Notification Configuration (Optional)
notifications:
  enabled: false
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender: ""
    password: ""
    recipients: []
