# Video Subtitle Generator Configuration

# Application settings
app:
  name: "Video Subtitle Generator"
  version: "1.0.0"
  output_dir: "output"
  temp_dir: "temp"
  jobs_dir: "jobs"
  logs_dir: "logs"

# Google Cloud Platform settings
gcp:
  # Your GCP project ID - REPLACE WITH YOUR PROJECT ID
  project_id: "your-gcp-project-id"
  
  # GCP region for Vertex AI
  location: "us-central1"
  
  # Authentication method: "service_account" or "adc"
  auth_method: "service_account"
  
  # Path to service account JSON file
  service_account_path: "./service-account.json"
  
  # Bucket configuration
  bucket_mode: "create_new"
  existing_bucket_name: "your-bucket-name"

# Vertex AI settings
vertex_ai:
  # Model to use for subtitle generation
  default_model: "gemini-2.5-pro-preview-05-06"

  
  # Generation parameters
  temperature: 0.2
  top_p: 0.95
  max_output_tokens: 8192
  
  # Safety settings - matching reference code
  safety_settings:
    - category: "HARM_CATEGORY_HATE_SPEECH"
      threshold: "BLOCK_NONE"
    - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
      threshold: "BLOCK_NONE"
    - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
      threshold: "BLOCK_NONE"
    - category: "HARM_CATEGORY_HARASSMENT"
      threshold: "BLOCK_NONE"

# Processing settings
processing:
  chunk_duration: 60
  parallel_workers: 4
  max_retries: 3
  retry_delay: 5
  timing_offset_ms: 0
  keep_temp_files: false
  keep_gcs_data: false

# Language settings
languages:
  source: "auto"  # Auto-detect source language
  subtitles:
    # Core mandatory languages
    core:
      eng:
        name: "English"
        method: "transcribe"
        default: true
      hin:
        name: "Hindi"
        method: "dual"
        default: true
      ben:
        name: "Bengali"
        method: "transcribe"
        default: true
    # Optional Indian languages
    indian:
      tel:
        name: "Telugu"
        method: "translate"
      mar:
        name: "Marathi"
        method: "translate"
      tam:
        name: "Tamil"
        method: "translate"
      guj:
        name: "Gujarati"
        method: "translate"
      kan:
        name: "Kannada"
        method: "translate"
      mal:
        name: "Malayalam"
        method: "translate"
      pun:
        name: "Punjabi"
        method: "translate"
      ori:
        name: "Odia"
        method: "translate"
      asm:
        name: "Assamese"
        method: "translate"
      urd:
        name: "Urdu"
        method: "translate"
      san:
        name: "Sanskrit"
        method: "translate"
      kok:
        name: "Konkani"
        method: "translate"
      nep:
        name: "Nepali"
        method: "translate"
      sit:
        name: "Sinhala"
        method: "translate"
      mai:
        name: "Maithili"
        method: "translate"
      bho:
        name: "Bhojpuri"
        method: "translate"
      raj:
        name: "Rajasthani"
        method: "translate"
      mag:
        name: "Magahi"
        method: "translate"

# System settings
system:
  supported_video_formats:
    - "mp4"
    - "avi"
    - "mkv"
    - "mov"
    - "webm"
  max_file_size_gb: 10
  log_level: "INFO"

# Advanced features configuration
advanced_features:
  # Enable advanced quality analysis (BLEU scores, sentiment analysis)
  enable_quality_analysis: true
  
  # Enable enhanced timing analysis (speech rate detection, pause detection)
  enable_timing_analysis: true
  
  # Enable multi-modal processing (visual context, speaker identification)
  enable_multimodal_processing: true
  
  # Quality analysis settings
  quality_analysis:
    bleu_score_threshold: 0.3      # Minimum acceptable BLEU score
    sentiment_threshold: 0.3       # Maximum sentiment difference allowed
    confidence_threshold: 0.7      # Minimum confidence for speech recognition
  
  # Timing analysis settings
  timing_analysis:
    target_reading_speed_wpm: 200  # Target words per minute
    min_pause_duration: 0.3        # Minimum pause duration to detect (seconds)
    speech_rate_tolerance: 0.2     # Tolerance for speech rate variations
  
  # Multi-modal processing settings
  multimodal_processing:
    enable_scene_detection: true   # Visual scene change detection
    enable_speaker_id: true        # Audio speaker identification
    enable_noise_filtering: true   # Background noise filtering
    scene_change_threshold: 0.7    # Threshold for scene change detection
    speaker_clustering_max: 6      # Maximum number of speakers to identify
