prompt: |
  Generate Punjabi subtitles by translating from the audio content.

  INSTRUCTIONS:
  - First understand the audio in English/Hindi/Bengali
  - Translate to Punjabi accurately maintaining context
  - Use Punjabi script (ਪੰਜਾਬੀ)
  - Format must be SRT with timestamps: hh:mm:ss,mmm --> hh:mm:ss,mmm
  - Maintain timing synchronization
  - Use natural Punjabi expressions

  Provide ONLY the SRT formatted subtitles in Punjabi, no additional text.