name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker compose build subtitle-generator

    - name: Create test directories
      run: |
        mkdir -p input output logs temp jobs

    - name: Create mock service account
      run: |
        echo '{"type":"service_account","project_id":"test"}' > service-account.json

    - name: Test Docker container startup
      run: |
        docker compose run --rm subtitle-generator \
          python -c "from src.health_checker import quick_health_check; print('Health check passed')"

    - name: Test Python environment
      run: |
        docker compose run --rm subtitle-generator \
          python -c "import sys; print(f'Python {sys.version}')"

    - name: Test FFmpeg availability
      run: |
        docker compose run --rm subtitle-generator \
          ffmpeg -version